version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.12"
  max_line_length = 88
  skip_doc_coverage = ["test"]
  
[[analyzers]]
name = "test-coverage"

  [analyzers.meta]
  coverage_threshold = 80
